import { afterEach, describe, expect, it } from 'vitest';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import * as yaml from 'js-yaml';
import {
  RUNTIME_V2_PRINCIPLE_BUDGET,
  SqliteActivationStateStore,
  SqliteConnection,
  getDefaultPdConfig,
  trimToBudget,
  renderPrinciplesToDirectives,
  type ActivatedPrinciple,
} from '@principles/core/runtime-v2';
import { escapeXml } from '@principles/core/prompt-builder';
import { buildActivePrinciplePromptContext } from '../src/index.js';

/**
 * AC-04 golden characterization (SPEC PD_PROMPT_CAPACITY_V1 §7).
 *
 * These expectations were generated by executing the CURRENT production
 * builders on the PRISTINE pre-change source (commit 9f55bbd0, dist built
 * from origin/main f330acb3) — see docs/audit/PD_PROMPT_CAPACITY_REALITY_
 * AUDIT_2026-10-07.md. Phase A/B changes to projection, console copy, and
 * write gates MUST NOT alter these bytes: candidate order, serialization,
 * budget accounting, rotation arithmetic, and the actually-injected set stay
 * identical. Changing one of these strings is an intentional behavior
 * contract change, not a test fix.
 */

const tempDirs: string[] = [];

function tempWorkspace(): string {
  const workspaceDir = fs.mkdtempSync(path.join(os.tmpdir(), 'pd-golden-char-'));
  tempDirs.push(workspaceDir);
  fs.mkdirSync(path.join(workspaceDir, '.pd'), { recursive: true });
  const config = getDefaultPdConfig();
  config.features.abstraction_layer_v1 = { ...config.features.abstraction_layer_v1, enabled: true };
  fs.writeFileSync(path.join(workspaceDir, '.pd', 'config.yaml'), yaml.dump(config), 'utf8');
  return workspaceDir;
}

afterEach(() => {
  for (const dir of tempDirs.splice(0)) {
    fs.rmSync(dir, { recursive: true, force: true, maxRetries: 3, retryDelay: 50 });
  }
});

const mk = (principleId: string, text: string): ActivatedPrinciple => ({
  principleId, text, artifactId: `art-${principleId}`, activationId: `act-${principleId}`,
});

const T01 = '回答前先复述任务目标与边界条件';
const T02 = '遇到 <tag> 与 & "quotes" 和 \'single\' 时先转义再输出';
const T03 = '完成后用 📌 一行自报改变了什么';
const T04 = 'A'.repeat(120);
const CASE: ActivatedPrinciple[] = [mk('T-01', T01), mk('T-02', T02), mk('T-03', T03), mk('T-04', T04)];

const DIRECTIVE_HEADER =
  '\n## 【ACTIVE BEHAVIOR DIRECTIVES】\n\n'
  + 'Active behavior directives are operating constraints learned from prior owner corrections. '
  + 'Each directive carries its authorization: authority="owner" (approved in the owner approval queue) '
  + 'or authority="system_policy" (auto-activated by low-risk policy).\n'
  + 'These directives are mandatory for this session unless they conflict with safety, security, or higher-priority system policy.\n'
  + 'For ambiguous coding or file-changing tasks, follow these directives before using mutating tools.\n\n';
const DIRECTIVE_NOTE = 'Note: These directives do not override safety, security, or core system policy.';
const SELF_REPORT_BLOCK =
  'Self-report (OWNER visibility): when a directive above actually changes what you do in this turn, append exactly ONE line at the end of your reply in this format:\n'
  + '📌 应用了你的原则「<directive id>」：<用一句话说明你这次做法有何不同>\n'
  + 'Use the directive\'s exact id attribute. At most one line per directive per session. Omit the line entirely if no directive changed your behavior.\n\n';

function directiveBlock(escapedText: string): string {
  return `<directive id="T-K" source="runtime_v2_activation">\nMANDATORY: ${escapedText}\n`
    + 'Apply this as an active behavior constraint. Do not treat this as background context.\n</directive>\n\n';
}

const escT01 = T01;
const escT02 = '遇到 &lt;tag&gt; 与 &amp; &quot;quotes&quot; 和 &apos;single&apos; 时先转义再输出';
const escT03 = T03;

async function seedWorkspace(workspaceDir: string, entries: ActivatedPrinciple[]): Promise<void> {
  const connection = new SqliteConnection({ workspaceDir });
  try {
    const base = Date.UTC(2026, 9, 7, 8, 0, 0);
    const insertArtifact = connection.getDb().prepare(`
      INSERT INTO pi_artifacts (artifact_id, artifact_kind, source_task_id, source_principle_id, source_rule_id, lineage_artifact_ids, validation_status, content_json, created_at, updated_at)
      VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    `);
    const store = new SqliteActivationStateStore(connection);
    for (let i = 0; i < entries.length; i += 1) {
      const p = entries[i];
      const at = new Date(base + i * 60_000).toISOString();
      insertArtifact.run(p.artifactId, 'principle', `task-${p.principleId}`, p.principleId, null, '[]', 'validated', JSON.stringify({ principleId: p.principleId, text: p.text }), at, at);
      await store.recordActivation({
        activationId: p.activationId, idempotencyKey: `${p.artifactId}::prompt`, artifactId: p.artifactId,
        channel: 'prompt', action: 'prompt_activate', targetRef: `ledger://${p.principleId}`,
        activatedAt: at, deactivatedAt: null,
      });
    }
  } finally {
    connection.close();
  }
}

describe('AC-04 golden characterization — production prompt builders must stay byte-identical', () => {
  it('list route FIFO: exact selected lines, order, and usedChars (CJK / XML escaping / emoji)', () => {
    const fifo = trimToBudget(CASE, RUNTIME_V2_PRINCIPLE_BUDGET, escapeXml);
    expect(fifo.lines).toEqual([
      'Runtime V2 activated principles:',
      `- [T-01] ${escT01}`,
      `- [T-02] ${escT02}`,
      `- [T-03] ${escT03}`,
      `- [T-04] ${T04}`,
    ]);
    expect(fifo.lines.join('\n').length).toBe(294);
    expect(fifo.truncated).toBe(false);
    expect([...fifo.injectedIds]).toEqual(['T-01', 'T-02', 'T-03', 'T-04']);
    expect(fifo.selectionPolicy).toBe('legacy_fifo_prefix_v1');
    expect(fifo.oversizedActivationIds).toEqual([]);
    expect(fifo.droppedActivationIds).toEqual([]);
  });

  it('list route final render (hooks/prompt.ts composition): exact full string, self-report off and on', () => {
    const fifo = trimToBudget(CASE, RUNTIME_V2_PRINCIPLE_BUDGET, escapeXml);
    const injected = CASE.filter((p) => fifo.injectedIds.has(p.principleId));
    const expected =
      DIRECTIVE_HEADER
      + directiveBlock(escT01).replaceAll('id="T-K"', 'id="T-01"')
      + directiveBlock(escT02).replaceAll('id="T-K"', 'id="T-02"')
      + directiveBlock(escT03).replaceAll('id="T-K"', 'id="T-03"')
      + directiveBlock(T04).replaceAll('id="T-K"', 'id="T-04"')
      + DIRECTIVE_NOTE;
    expect(renderPrinciplesToDirectives(injected, fifo.injectedIds, { escapeFn: escapeXml, selfReportInstruction: false }))
      .toBe(expected);
    expect(renderPrinciplesToDirectives(injected, fifo.injectedIds, { escapeFn: escapeXml, selfReportInstruction: true }))
      .toBe(expected.replace(DIRECTIVE_NOTE, SELF_REPORT_BLOCK + DIRECTIVE_NOTE));
  });

  it('list route fair rotation: every round key selects the same set in rotated order with identical usage', () => {
    for (const [k, expectedIds] of [
      [0, ['T-01', 'T-02', 'T-03', 'T-04']],
      [1, ['T-02', 'T-03', 'T-04', 'T-01']],
      [2, ['T-03', 'T-04', 'T-01', 'T-02']],
      [3, ['T-04', 'T-01', 'T-02', 'T-03']],
    ] as const) {
      const t = trimToBudget(CASE, RUNTIME_V2_PRINCIPLE_BUDGET, escapeXml, k);
      expect([...t.injectedIds]).toEqual([...expectedIds]);
      expect(t.selectionPolicy).toBe('fair_rotation_v1');
      expect(t.rotationStartIndex).toBe(k);
      expect(t.lines.join('\n').length).toBe(294);
      expect(t.truncated).toBe(false);
    }
  });

  it('list route budget boundary: header+entry+newline exactly filling the budget injects; one char more is oversized', () => {
    const header = 'Runtime V2 activated principles:';
    // header + '\n' + '- [B-EXACT] ' + text + '\n' === 2000
    const b1TextLen = RUNTIME_V2_PRINCIPLE_BUDGET - header.length - 1 - '- [B-EXACT] '.length - 1;
    const b1 = trimToBudget([mk('B-EXACT', 'x'.repeat(b1TextLen))], RUNTIME_V2_PRINCIPLE_BUDGET, escapeXml);
    expect(b1.lines.join('\n').length).toBe(1999);
    expect([...b1.injectedIds]).toEqual(['B-EXACT']);
    expect(b1.oversizedActivationIds).toEqual([]);
    const b2 = trimToBudget([mk('B-OVER1', 'x'.repeat(b1TextLen + 1))], RUNTIME_V2_PRINCIPLE_BUDGET, escapeXml);
    expect(b2.lines.join('\n').length).toBe(2000);
    expect([...b2.injectedIds]).toEqual(['B-OVER1']);
    expect(b2.oversizedActivationIds).toEqual([]);
    // Truly oversized alone: FIFO sets truncated and classifies oversized.
    const ov = trimToBudget([mk('OV-1', 'o'.repeat(2000))], RUNTIME_V2_PRINCIPLE_BUDGET, escapeXml);
    expect([...ov.injectedIds]).toEqual([]);
    expect(ov.oversizedActivationIds).toEqual(['act-OV-1']);
    expect(ov.truncated).toBe(true);
  });

  it('shared route FIFO (production builder): exact additionalContext bytes, order, and policy', async () => {
    const workspaceDir = tempWorkspace();
    await seedWorkspace(workspaceDir, CASE);
    const context = await buildActivePrinciplePromptContext({ workspaceDir });
    const expected =
      DIRECTIVE_HEADER
      + directiveBlock(escT01).replaceAll('id="T-K"', 'id="T-01"')
      + directiveBlock(escT02).replaceAll('id="T-K"', 'id="T-02"')
      + directiveBlock(escT03).replaceAll('id="T-K"', 'id="T-03"')
      + directiveBlock(T04).replaceAll('id="T-K"', 'id="T-04"')
      + DIRECTIVE_NOTE;
    expect(context.additionalContext).toBe(expected);
    expect(context.additionalContext.length).toBe(1476);
    expect(context.principleIds).toEqual(['T-01', 'T-02', 'T-03', 'T-04']);
    expect(context.activationIds).toEqual(['act-T-01', 'act-T-02', 'act-T-03', 'act-T-04']);
    expect(context.truncated).toBe(false);
    expect(context.selectionPolicy).toBe('legacy_fifo_prefix_v1');
  });

  it('shared route rotation (roundKey=2): exact bytes with rotated directive order', async () => {
    const workspaceDir = tempWorkspace();
    await seedWorkspace(workspaceDir, CASE);
    const context = await buildActivePrinciplePromptContext({ workspaceDir, roundKey: 2 });
    const expected =
      DIRECTIVE_HEADER
      + directiveBlock(escT03).replaceAll('id="T-K"', 'id="T-03"')
      + directiveBlock(T04).replaceAll('id="T-K"', 'id="T-04"')
      + directiveBlock(escT01).replaceAll('id="T-K"', 'id="T-01"')
      + directiveBlock(escT02).replaceAll('id="T-K"', 'id="T-02"')
      + DIRECTIVE_NOTE;
    expect(context.additionalContext).toBe(expected);
    expect(context.principleIds).toEqual(['T-03', 'T-04', 'T-01', 'T-02']);
    expect(context.selectionPolicy).toBe('fair_rotation_v1');
    expect(context.rotationStartIndex).toBe(2);
  });

  it('AC-02 root scenario: shared route reports oversizedActivationIds with truncated=false (no other drop)', async () => {
    const workspaceDir = tempWorkspace();
    const entries = [...CASE, mk('OV-S', 'y'.repeat(1980))];
    await seedWorkspace(workspaceDir, entries);
    const context = await buildActivePrinciplePromptContext({ workspaceDir });
    expect(context.oversizedActivationIds).toEqual(['act-OV-S']);
    expect(context.droppedActivationIds ?? []).toEqual([]);
    expect(context.truncated).toBe(false);
    expect(context.principleIds).toEqual(['T-01', 'T-02', 'T-03', 'T-04']);
    expect(context.additionalContext.length).toBe(1476);
  });
});
