import json
from pathlib import Path

update = {
    'nodes': [
        {'id': 'correction-cue-learner', 'label': 'Correction Cue Learner', 'file_type': 'code', 'source_file': 'packages/openclaw-plugin/src/core/correction-cue-learner.ts', 'source_location': 'L1-100', 'source_url': None, 'captured_at': '2026-04-17', 'author': None, 'contributor': 'csuzngjh'},
        {'id': 'correction-keyword-store', 'label': 'CorrectionKeywordStore', 'file_type': 'code', 'source_file': 'packages/openclaw-plugin/src/core/correction-cue-learner.ts', 'source_location': 'L14-70', 'source_url': None, 'captured_at': '2026-04-17', 'author': None, 'contributor': 'csuzngjh'},
        {'id': 'loadcorrectionkeywordstore', 'label': 'loadCorrectionKeywordStore()', 'file_type': 'code', 'source_file': 'packages/openclaw-plugin/src/core/correction-cue-learner.ts', 'source_location': 'L80-100', 'source_url': None, 'captured_at': '2026-04-17', 'author': None, 'contributor': 'csuzngjh'},
        {'id': 'atomic-write-correction', 'label': 'Atomic Write (Correction Store)', 'file_type': 'code', 'source_file': 'packages/openclaw-plugin/src/core/correction-cue-learner.ts', 'source_location': 'L8-12', 'source_url': None, 'captured_at': '2026-04-17', 'author': None, 'contributor': 'csuzngjh'},
        {'id': 'correction-seed-keywords', 'label': 'CORRECTION_SEED_KEYWORDS (16 terms)', 'file_type': 'code', 'source_file': 'packages/openclaw-plugin/src/core/correction-cue-learner.ts', 'source_location': 'L21-27', 'source_url': None, 'captured_at': '2026-04-17', 'author': None, 'contributor': 'csuzngjh'},
        {'id': 'keyword-weight-bounds', 'label': 'Keyword Weight Bounds (0.1-0.9)', 'file_type': 'code', 'source_file': 'packages/openclaw-plugin/src/core/correction-cue-learner.ts', 'source_location': 'L32-34', 'source_url': None, 'captured_at': '2026-04-17', 'author': None, 'contributor': 'csuzngjh'},
        {'id': 'max-correction-keywords', 'label': 'MAX_CORRECTION_KEYWORDS (200 cap)', 'file_type': 'code', 'source_file': 'packages/openclaw-plugin/src/core/correction-cue-learner.ts', 'source_location': 'L22', 'source_url': None, 'captured_at': '2026-04-17', 'author': None, 'contributor': 'csuzngjh'},
        {'id': 'evolution-worker-handleaftertoolcall', 'label': 'handleAfterToolCall()', 'file_type': 'code', 'source_file': 'packages/openclaw-plugin/src/service/evolution-worker.ts', 'source_location': 'L49-200', 'source_url': None, 'captured_at': '2026-04-17', 'author': None, 'contributor': 'csuzngjh'},
        {'id': 'pain-event-emission', 'label': 'Pain Event Emission (emitPainDetectedEvent)', 'file_type': 'code', 'source_file': 'packages/openclaw-plugin/src/service/evolution-worker.ts', 'source_location': 'L37-43', 'source_url': None, 'captured_at': '2026-04-17', 'author': None, 'contributor': 'csuzngjh'},
        {'id': 'pain-flag-emission', 'label': 'Pain Flag Emission', 'file_type': 'code', 'source_file': 'packages/openclaw-plugin/src/hooks/pain.ts', 'source_location': 'L1-100', 'source_url': None, 'captured_at': '2026-04-17', 'author': None, 'contributor': 'csuzngjh'},
        {'id': 'queue-io', 'label': 'Queue I/O (loadEvolutionQueue, saveEvolutionQueue)', 'file_type': 'code', 'source_file': 'packages/openclaw-plugin/src/hooks/pain.ts', 'source_location': 'L23-29', 'source_url': None, 'captured_at': '2026-04-17', 'author': None, 'contributor': 'csuzngjh'},
        {'id': 'pain-signal-validation', 'label': 'PainSignal Validation (validatePainSignal)', 'file_type': 'code', 'source_file': 'packages/openclaw-plugin/src/hooks/pain.ts', 'source_location': 'L21', 'source_url': None, 'captured_at': '2026-04-17', 'author': None, 'contributor': 'csuzngjh'},
        {'id': 'keyword-opt-cooldown', 'label': 'Keyword Optimization Cooldown (checkKeywordOptCooldown)', 'file_type': 'code', 'source_file': 'packages/openclaw-plugin/src/core/correction-cue-learner.ts', 'source_location': 'L24', 'source_url': None, 'captured_at': '2026-04-17', 'author': None, 'contributor': 'csuzngjh'},
        {'id': 'correction-cache-invalidation', 'label': 'Cache Invalidation after Write (D-05)', 'file_type': 'code', 'source_file': 'packages/openclaw-plugin/src/core/correction-cue-learner.ts', 'source_location': 'L37-52', 'source_url': None, 'captured_at': '2026-04-17', 'author': None, 'contributor': 'csuzngjh'},
    ],
    'edges': [
        {'source': 'correction-cue-learner', 'target': 'correction-keyword-store', 'relation': 'defines', 'confidence': 'EXTRACTED', 'confidence_score': 1.0, 'source_file': 'packages/openclaw-plugin/src/core/correction-cue-learner.ts', 'source_location': 'L14-19', 'weight': 1.0},
        {'source': 'correction-cue-learner', 'target': 'loadcorrectionkeywordstore', 'relation': 'implements', 'confidence': 'EXTRACTED', 'confidence_score': 1.0, 'source_file': 'packages/openclaw-plugin/src/core/correction-cue-learner.ts', 'source_location': 'L80-100', 'weight': 1.0},
        {'source': 'correction-keyword-store', 'target': 'correction-seed-keywords', 'relation': 'populated_by', 'confidence': 'EXTRACTED', 'confidence_score': 1.0, 'source_file': 'packages/openclaw-plugin/src/core/correction-cue-learner.ts', 'source_location': 'L62-70', 'weight': 1.0},
        {'source': 'correction-keyword-store', 'target': 'max-correction-keywords', 'relation': 'bounded_by', 'confidence': 'EXTRACTED', 'confidence_score': 1.0, 'source_file': 'packages/openclaw-plugin/src/core/correction-cue-learner.ts', 'source_location': 'L22', 'weight': 1.0},
        {'source': 'correction-keyword-store', 'target': 'keyword-weight-bounds', 'relation': 'constrains', 'confidence': 'EXTRACTED', 'confidence_score': 1.0, 'source_file': 'packages/openclaw-plugin/src/core/correction-cue-learner.ts', 'source_location': 'L32-34', 'weight': 1.0},
        {'source': 'evolution-worker-handleaftertoolcall', 'target': 'pain-event-emission', 'relation': 'calls', 'confidence': 'EXTRACTED', 'confidence_score': 1.0, 'source_file': 'packages/openclaw-plugin/src/service/evolution-worker.ts', 'source_location': 'L37-43', 'weight': 1.0},
        {'source': 'evolution-worker-handleaftertoolcall', 'target': 'pain-flag-emission', 'relation': 'coordinates_with', 'confidence': 'INFERRED', 'confidence_score': 0.8, 'source_file': 'packages/openclaw-plugin/src/service/evolution-worker.ts', 'source_location': 'L49-100', 'weight': 1.0},
        {'source': 'evolution-worker-handleaftertoolcall', 'target': 'queue-io', 'relation': 'uses', 'confidence': 'EXTRACTED', 'confidence_score': 1.0, 'source_file': 'packages/openclaw-plugin/src/hooks/pain.ts', 'source_location': 'L23-29', 'weight': 1.0},
        {'source': 'pain-flag-emission', 'target': 'queue-io', 'relation': 'exports_to', 'confidence': 'EXTRACTED', 'confidence_score': 1.0, 'source_file': 'packages/openclaw-plugin/src/hooks/pain.ts', 'source_location': 'L23-29', 'weight': 1.0},
        {'source': 'pain-flag-emission', 'target': 'pain-signal-validation', 'relation': 'calls', 'confidence': 'EXTRACTED', 'confidence_score': 1.0, 'source_file': 'packages/openclaw-plugin/src/hooks/pain.ts', 'source_location': 'L21', 'weight': 1.0},
        {'source': 'correction-cue-learner', 'target': 'keyword-opt-cooldown', 'relation': 'uses', 'confidence': 'EXTRACTED', 'confidence_score': 1.0, 'source_file': 'packages/openclaw-plugin/src/core/correction-cue-learner.ts', 'source_location': 'L24', 'weight': 1.0},
        {'source': 'loadcorrectionkeywordstore', 'target': 'correction-cache-invalidation', 'relation': 'enforces', 'confidence': 'EXTRACTED', 'confidence_score': 1.0, 'source_file': 'packages/openclaw-plugin/src/core/correction-cue-learner.ts', 'source_location': 'L37-52', 'weight': 1.0},
        {'source': 'atomic-write-correction', 'target': 'correction-cache-invalidation', 'relation': 'triggers', 'confidence': 'EXTRACTED', 'confidence_score': 1.0, 'source_file': 'packages/openclaw-plugin/src/core/correction-cue-learner.ts', 'source_location': 'L37-52', 'weight': 1.0},
    ],
    'hyperedges': [
        {'id': 'correction_fp_feedback_loop', 'label': 'Correction FP Feedback Loop', 'nodes': ['correction-cue-learner', 'correction-keyword-store', 'correction-seed-keywords', 'keyword-opt-cooldown', 'correction-cache-invalidation'], 'relation': 'participate_in', 'confidence': 'EXTRACTED', 'confidence_score': 1.0, 'source_file': 'packages/openclaw-plugin/src/core/correction-cue-learner.ts'},
        {'id': 'pain_queue_pipeline', 'label': 'Pain Queue Processing Pipeline', 'nodes': ['evolution-worker-handleaftertoolcall', 'pain-event-emission', 'pain-flag-emission', 'queue-io', 'pain-signal-validation'], 'relation': 'participate_in', 'confidence': 'EXTRACTED', 'confidence_score': 1.0, 'source_file': 'packages/openclaw-plugin/src/service/evolution-worker.ts'},
    ]
}

Path('D:/Code/principles/.graphify_update.json').write_text(json.dumps(update, indent=2, ensure_ascii=False), encoding='utf-8')
print(f'Update ready: {len(update["nodes"])} nodes, {len(update["edges"])} edges, {len(update["hyperedges"])} hyperedges')
