#!/bin/bash
# ============================================================================
# 报告对比脚本
# ============================================================================
# 用途：对比两次Agent生成的报告，评估质量变化
# ============================================================================

set -e

# 加载测试环境配置
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/config/test-env.sh"

# 参数
REPORT1="$1"
REPORT2="$2"
OUTPUT="$3"  # 可选：输出对比报告路径

if [ -z "$REPORT1" ] || [ -z "$REPORT2" ]; then
    echo "Usage: $0 <report1> <report2> [output_file]"
    exit 1
fi

if [ ! -f "$REPORT1" ]; then
    echo "❌ Error: File not found: $REPORT1"
    exit 1
fi

if [ ! -f "$REPORT2" ]; then
    echo "❌ Error: File not found: $REPORT2"
    exit 1
fi

# ============================================================================
# 对比分析
# ============================================================================

# 文件统计对比
compare_stats() {
    local size1=$(wc -c < "$REPORT1")
    local size2=$(wc -c < "$REPORT2")
    local words1=$(wc -w < "$REPORT1")
    local words2=$(wc -w < "$REPORT2")
    local lines1=$(wc -l < "$REPORT1")
    local lines2=$(wc -l < "$REPORT2")

    local size_diff=$((size2 - size1))
    local words_diff=$((words2 - words1))
    local lines_diff=$((lines2 - lines1))

    local size_change=$((size_diff * 100 / size1))
    local words_change=$((words_diff * 100 / words1))

    echo "## File Statistics Comparison"
    echo ""
    echo "| Metric | Report 1 | Report 2 | Change | Trend |"
    echo "|--------|----------|----------|--------|-------|"
    echo "| Size | $size1 bytes | $size2 bytes | $size_diff bytes (${size_change}%) | $( [ "$size_diff" -gt 0 ] && echo "📈" || echo "📉" ) |"
    echo "| Words | $words1 | $words2 | $words_diff (${words_change}%) | $( [ "$words_diff" -gt 0 ] && echo "📈" || echo "📉" ) |"
    echo "| Lines | $lines1 | $lines2 | $lines_diff | $( [ "$lines_diff" -gt 0 ] && echo "📈" || echo "📉" ) |"
    echo ""
}

# 章节对比
compare_sections() {
    echo "## Section Comparison"
    echo ""

    local sections=("故事节奏分析" "情节连贯性" "发现的问题" "评分" "改进建议")

    echo "| Section | Report 1 | Report 2 |"
    echo "|---------|----------|----------|"

    for section in "${sections[@]}"; do
        local has1=$(grep -q "## $section" "$REPORT1" 2>/dev/null && echo "✅" || echo "❌")
        local has2=$(grep -q "## $section" "$REPORT2" 2>/dev/null && echo "✅" || echo "❌")
        echo "| $section | $has1 | $has2 |"
    done

    echo ""
}

# 问题发现对比
compare_issues() {
    echo "## Issues Found"
    echo ""

    local p0_1=$(grep -c "P0" "$REPORT1" 2>/dev/null || echo "0")
    local p1_1=$(grep -c "P1" "$REPORT1" 2>/dev/null || echo "0")
    local p2_1=$(grep -c "P2" "$REPORT1" 2>/dev/null || echo "0")
    local total_1=$((p0_1 + p1_1 + p2_1))

    local p0_2=$(grep -c "P0" "$REPORT2" 2>/dev/null || echo "0")
    local p1_2=$(grep -c "P1" "$REPORT2" 2>/dev/null || echo "0")
    local p2_2=$(grep -c "P2" "$REPORT2" 2>/dev/null || echo "0")
    local total_2=$((p0_2 + p1_2 + p2_2))

    echo "| Priority | Report 1 | Report 2 | Change |"
    echo "|----------|----------|----------|--------|"
    echo "| P0 (Critical) | $p0_1 | $p0_2 | $((p0_2 - p0_1)) |"
    echo "| P1 (High) | $p1_1 | $p1_2 | $((p1_2 - p1_1)) |"
    echo "| P2 (Medium) | $p2_1 | $p2_2 | $((p2_2 - p2_1)) |"
    echo "| **Total** | **$total_1** | **$total_2** | **$((total_2 - total_1))** |"
    echo ""
}

# 内容diff（前100行）
content_diff() {
    echo "## Content Differences (First 100 lines)"
    echo ""
    echo '```diff'
    diff -u "$REPORT1" "$REPORT2" 2>/dev/null | head -100 || echo "Files are identical"
    echo '```'
    echo ""
}

# 评分对比
compare_scores() {
    echo "## Quality Scores"
    echo ""

    local score1=$("$SCRIPT_DIR/score-report.sh" "$REPORT1" 2>/dev/null | grep "Total Score:" | awk '{print $3}' || echo "N/A")
    local score2=$("$SCRIPT_DIR/score-report.sh" "$REPORT2" 2>/dev/null | grep "Total Score:" | awk '{print $3}' || echo "N/A")

    echo "| Report | Score | Grade |"
    echo "|--------|-------|-------|"
    echo "| Report 1 | $score1/100 | - |"
    echo "| Report 2 | $score2/100 | - |"
    echo ""
}

# 生成对比报告
generate_comparison_report() {
    local timestamp=$(date +%Y%m%d-%H%M%S)
    local default_output="$TEST_REPORTS_DIR/comparison-$timestamp.md"
    local output_file="${OUTPUT:-$default_output}"

    mkdir -p "$TEST_REPORTS_DIR"

    cat > "$output_file" << EOF
# Report Comparison

**Date**: $(date)
**Report 1**: \`$REPORT1\`
**Report 2**: \`$REPORT2\`

---

$(compare_stats)
$(compare_sections)
$(compare_issues)
$(compare_scores)
$(content_diff)

---

**Generated by**: \`compare-reports.sh\`
EOF

    echo "📄 Comparison report saved to: $output_file"
}

# ============================================================================
# 主流程
# ============================================================================

main() {
    echo "╔════════════════════════════════════════════════════════════╗"
    echo "║                Report Comparison Tool                      ║"
    echo "╚════════════════════════════════════════════════════════════╝"
    echo ""
    echo "Report 1: $REPORT1"
    echo "Report 2: $REPORT2"
    echo ""

    # 打印对比结果到终端
    compare_stats
    compare_sections
    compare_issues

    # 生成完整报告
    generate_comparison_report

    echo ""
    echo "✅ Comparison complete!"
}

main "$@"
