/**
 * Template Generator for Principle Compiler
 *
 * Generates RuleHost sandbox code from PainPattern descriptors.
 * Produces self-contained JS modules with `export const meta` and
 * `export function evaluate(input)` that can be loaded at runtime.
 */

export interface PainPattern {
  toolName: string;
  pathRegex?: string;
  commandRegex?: string;
  contentRegex?: string;
  errorType?: string;
}

/**
 * Derives the auto-rule display name from a principle ID.
 * "P_066" => "Auto_P_066", "P_010" => "Auto_P_010"
 */
function toAutoName(principleId: string): string {
  return `Auto_${principleId}`;
}

/**
 * Derives the auto-rule ID from a principle ID.
 * "P_066" => "R_P066_auto", "P_010" => "R_P010_auto"
 */
function toAutoRuleId(principleId: string): string {
  const num = principleId.replace(/^P_/, '');
  return `R_P${num}_auto`;
}

/**
 * Builds a single `if` branch for a pain pattern.
 *
 * - bash tool: checks toolName + commandRegex against paramsSummary.command
 * - write/edit tool: checks toolName + pathRegex + contentRegex (with new_string fallback)
 * - any tool with pathRegex: adds path check
 */
function buildBranch(principleId: string, pattern: PainPattern): string {
  const conditions: string[] = [];

  conditions.push(`input.action.toolName === '${pattern.toolName}'`);

  if (pattern.pathRegex) {
    conditions.push(`/${pattern.pathRegex}/.test(input.action.normalizedPath || '')`);
  }

  if (pattern.commandRegex) {
    conditions.push(`/${pattern.commandRegex}/.test(input.action.paramsSummary.command || '')`);
  }

  if (pattern.contentRegex) {
    conditions.push(
      `/${pattern.contentRegex}/.test(input.action.paramsSummary.content || input.action.paramsSummary.new_string || '')`,
    );
  }

  const guard = conditions.join(' && ');
  const reason = `[${principleId}] Blocked by auto-generated rule`;

  return (
    `  if (${guard}) {\n` +
    `    return { decision: 'block', matched: true, reason: '${reason}' };\n` +
    `  }`
  );
}

/**
 * Generates sandbox-ready JS code from a principle ID and pain patterns.
 *
 * Returns `null` when `patterns` is empty.
 * The returned string is a self-contained ES module with:
 *   - `export const meta` — rule metadata
 *   - `export function evaluate(input)` — returns `{ matched: true, decision: 'block' }` or `{ matched: false }`
 */
export function generateFromTemplate(
  principleId: string,
  coversCondition: string,
  patterns: PainPattern[],
): string | null {
  if (patterns.length === 0) {
    return null;
  }

  const name = toAutoName(principleId);
  const ruleId = toAutoRuleId(principleId);
  const compiledAt = new Date().toISOString();

  const branches = patterns
    .map((p) => buildBranch(principleId, p))
    .join('\n');

  return (
    `// Auto-generated by Principle Compiler\n` +
    `export const meta = {\n` +
    `  name: '${name}',\n` +
    `  version: '1.0.0',\n` +
    `  ruleId: '${ruleId}',\n` +
    `  coversCondition: '${coversCondition}',\n` +
    `  compiledAt: '${compiledAt}',\n` +
    `  sourcePrincipleId: '${principleId}',\n` +
    `};\n\n` +
    `export function evaluate(input) {\n` +
    `${branches}\n` +
    `  return { matched: false };\n` +
    `}\n`
  );
}
