/**
 * Template Generator for Principle Compiler
 *
 * Generates RuleHost sandbox code from PainPattern descriptors.
 * Produces self-contained JS modules with `export const meta` and
 * `export function evaluate(input)` that can be loaded at runtime.
 *
 * SECURITY: All interpolated values use JSON.stringify or safe helpers
 * to prevent code injection through principleId, coversCondition, or regex patterns.
 */

export interface PainPattern {
  toolName: string;
  pathRegex?: string;
  commandRegex?: string;
  contentRegex?: string;
  errorType?: string;
}

/**
 * Derives the auto-rule display name from a principle ID.
 */
function toAutoName(principleId: string): string {
  return `Auto_${principleId}`;
}

/**
 * Derives the auto-rule ID from a principle ID.
 * Must match ledger-registrar convention: "P_066" => "R_P_066_auto"
 */
function toAutoRuleId(principleId: string): string {
  return `R_${principleId}_auto`;
}

/**
 * Builds a single `if` branch for a pain pattern.
 *
 * SECURITY: Uses `new RegExp(JSON.stringify(...))` instead of regex literals
 * to prevent code injection through pathRegex/commandRegex/contentRegex values.
 * principleId in reason uses JSON.stringify to prevent string breakout.
 */
function buildBranch(principleId: string, pattern: PainPattern): string {
  const conditions: string[] = [];

  conditions.push(`input.action.toolName === ${JSON.stringify(pattern.toolName)}`);

  if (pattern.pathRegex) {
    conditions.push(`new RegExp(${JSON.stringify(pattern.pathRegex)}).test(input.action.normalizedPath || '')`);
  }

  if (pattern.commandRegex) {
    conditions.push(`new RegExp(${JSON.stringify(pattern.commandRegex)}).test(input.action.paramsSummary.command || '')`);
  }

  if (pattern.contentRegex) {
    conditions.push(
      `new RegExp(${JSON.stringify(pattern.contentRegex)}).test(input.action.paramsSummary.content || input.action.paramsSummary.new_string || '')`,
    );
  }

  const guard = conditions.join(' && ');
  const reason = `[${principleId}] Blocked by auto-generated rule`;

  return (
    `  if (${guard}) {\n` +
    `    return { decision: 'block', matched: true, reason: ${JSON.stringify(reason)} };\n` +
    `  }`
  );
}

/**
 * Generates sandbox-ready JS code from a principle ID and pain patterns.
 *
 * Returns `null` when `patterns` is empty.
 */
export function generateFromTemplate(
  principleId: string,
  coversCondition: string,
  patterns: PainPattern[],
): string | null {
  if (patterns.length === 0) {
    return null;
  }

  const name = toAutoName(principleId);
  const ruleId = toAutoRuleId(principleId);
  const compiledAt = new Date().toISOString();

  const branches = patterns
    .map((p) => buildBranch(principleId, p))
    .join('\n');

  return (
    `// Auto-generated by Principle Compiler\n` +
    `export const meta = {\n` +
    `  name: ${JSON.stringify(name)},\n` +
    `  version: '1.0.0',\n` +
    `  ruleId: ${JSON.stringify(ruleId)},\n` +
    `  coversCondition: ${JSON.stringify(coversCondition)},\n` +
    `  compiledAt: ${JSON.stringify(compiledAt)},\n` +
    `  sourcePrincipleId: ${JSON.stringify(principleId)},\n` +
    `};\n\n` +
    `export function evaluate(input) {\n` +
    `${branches}\n` +
    `  return { matched: false };\n` +
    `}\n`
  );
}
