/**
 * pd runtime init — Initialize all PD SQLite databases for a workspace.
 *
 * Creates state.db, trajectory.db, and subagent_workflows.db with full schema
 * (tables + indexes + views + migrations). Idempotent: safe to run on existing
 * workspaces (all CREATE statements use IF NOT EXISTS).
 *
 * Output contract (cli-1 strict-json, cli-4 dry-run/confirm mutex, cli-6 nextAction):
 * - Default mode is --dry-run (no writes); use --confirm to actually initialize.
 * - --json emits a single parseable JSON object on stdout.
 * - Failures emit { ok: false, reason, nextAction } with exit code 1.
 *
 * ERR refs:
 * - ERR-001/ERR-005: no `as` casts; DB rows typed via type guards
 * - ERR-002: degraded paths include reason + nextAction
 * - ERR-009/ERR-010: missing required fields fail loud
 * - ERR-014: safe JSON.stringify on known output shapes
 */

import * as path from 'path';
import * as fs from 'fs';
import * as yaml from 'js-yaml';
import { SqliteConnection, SchemaConformanceReadModel } from '@principles/core/runtime-v2';
import { getDefaultPdConfig, validatePdConfig } from '@principles/core/runtime-v2';
import { initTrajectorySchema, initWorkflowSchema } from 'principles-disciple';
import { resolveWorkspaceDir } from '../resolve-workspace.js';
import { emitResult, emitFlagConflict, emitError } from '../services/cli-output.js';

// ── Constants ─────────────────────────────────────────────────────────────────

const CONFIG_DIR = '.pd';
const CONFIG_FILENAME = 'config.yaml';
const CONFIG_HEADER =
  `# PD Runtime Configuration — single source of truth (.pd/config.yaml, ADR-0016)\n` +
  `# Auto-generated by 'pd runtime init'. Existing config files are never overwritten.\n` +
  `# Edit to configure feature flags, runtime profiles, internal agents, and UI.\n`;

/**
 * Type guard for Node.js errno errors (rc-2: no `as` on caught unknown).
 * Mirrors principle-tree-ledger.ts — uses Object.hasOwn, not `in`.
 * Structural type (not NodeJS.ErrnoException) to avoid the NodeJS global,
 * which is not defined in this package's eslint config.
 * Needed to detect EEXIST from the atomic exclusive write below.
 */
interface ErrnoExceptionLike {
  code?: string;
}

function isErrnoException(value: unknown): value is ErrnoExceptionLike {
  return typeof value === 'object' && value !== null && Object.hasOwn(value, 'code');
}

// ── Output types ─────────────────────────────────────────────────────────────

export interface DatabaseInitResult {
  name: string;
  path: string;
  tables: string[];
  status: 'initialized' | 'verified' | 'skipped' | 'failed';
  warnings: string[];
}

export interface ConfigInitResult {
  path: string;
  status: 'initialized' | 'skipped' | 'failed' | 'verified';
  warnings: string[];
}

export interface RuntimeInitOutput {
  ok: boolean;
  mode: 'dry-run' | 'confirm';
  workspace: string;
  databases: DatabaseInitResult[];
  config?: ConfigInitResult;
  warnings: string[];
  reason?: string;
  nextAction?: string;
}

// ── Build output ─────────────────────────────────────────────────────────────

const DB_NAMES = {
  state: 'state.db',
  trajectory: 'trajectory.db',
  workflow: 'subagent_workflows.db',
} as const;

// ── Config file generation ─────────────────────────────────────────────────────

/**
 * Build a clean YAML representation of the default PD config, injecting the
 * workspace.default path so that discoverWorkspaceDefault() can find it.
 *
 * PRI-645: `features` is a sparse map — the registry (DEFAULT_FEATURE_FLAGS)
 * owns every default value and computeEffectivePdConfig() fills missing flags
 * at read time. Materializing the full registry snapshot here would freeze
 * today's defaults against future graduation flips. An empty map is fully
 * valid (validatePdConfig only requires the section to be an object) and
 * means "every flag follows its registry default".
 *
 * Returns the YAML string (with header comment) for writing to disk.
 */
function buildConfigYaml(workspaceDir: string): string {
  const config = getDefaultPdConfig();
  const yamlObj: Record<string, unknown> = {
    version: config.version,
    workspace: {
      default: workspaceDir,
    },
    features: {},
    runtimeProfiles: config.runtimeProfiles,
    internalAgents: config.internalAgents,
    ui: config.ui,
  };
  return CONFIG_HEADER + yaml.dump(yamlObj, {
    indent: 2,
    lineWidth: 120,
    noRefs: true,
    sortKeys: false,
    quotingType: '"',
    forceQuotes: false,
  });
}

/**
 * Generate and write .pd/config.yaml if it does not already exist.
 * Validates the generated file with a round-trip parse+validate check.
 */
function buildConfigInitResult(workspaceDir: string, confirm: boolean): ConfigInitResult {
  const configPath = path.join(workspaceDir, CONFIG_DIR, CONFIG_FILENAME);
  const warnings: string[] = [];

  if (!confirm) {
    return { path: configPath, status: 'skipped', warnings: [] };
  }

  // Ensure .pd directory exists
  const configDir = path.dirname(configPath);
  try {
    fs.mkdirSync(configDir, { recursive: true });
  } catch (err) {
    const reason = err instanceof Error ? err.message : String(err);
    return { path: configPath, status: 'failed', warnings: [`Failed to create ${configDir}: ${reason}`] };
  }

  // Build and write YAML
  let yamlContent: string;
  try {
    yamlContent = buildConfigYaml(workspaceDir);
  } catch (err) {
    const reason = err instanceof Error ? err.message : String(err);
    return { path: configPath, status: 'failed', warnings: [`Failed to build config YAML: ${reason}`] };
  }

  try {
    // Atomic exclusive create ('wx'): the write itself is the authoritative
    // existence check — fails with EEXIST if the file already exists (from a
    // previous run or a concurrent process). No existsSync pre-check, so there
    // is no TOCTOU window and the "never overwrite existing config" contract
    // is race-free (CodeQL js/race-condition).
    fs.writeFileSync(configPath, yamlContent, { encoding: 'utf8', flag: 'wx' });
  } catch (err) {
    if (isErrnoException(err) && err.code === 'EEXIST') {
      return { path: configPath, status: 'skipped', warnings: ['config.yaml already exists, skipped'] };
    }
    const reason = err instanceof Error ? err.message : String(err);
    return { path: configPath, status: 'failed', warnings: [`Failed to write ${configPath}: ${reason}`] };
  }

  // Round-trip validation: read back, parse, validate
  try {
    const raw = fs.readFileSync(configPath, 'utf8');
    const parsed: unknown = yaml.load(raw, { schema: yaml.JSON_SCHEMA });
    const validationResult = validatePdConfig(parsed);
    if (!validationResult.ok) {
      warnings.push(`config.yaml round-trip validation produced ${validationResult.errors.length} warnings`);
      for (const ve of validationResult.errors) {
        warnings.push(`  [${ve.path}] ${ve.reason} — ${ve.nextAction}`);
      }
    }
  } catch (err) {
    // Non-fatal: proceed even if round-trip check fails
    warnings.push(`config.yaml round-trip check skipped: ${err instanceof Error ? err.message : String(err)}`);
  }

  return { path: configPath, status: 'initialized', warnings };
}

export function buildRuntimeInitOutput(workspaceDir: string, confirm: boolean): RuntimeInitOutput {
  const resolvedWorkspace = path.resolve(workspaceDir);
  const warnings: string[] = [];
  const databases: DatabaseInitResult[] = [];

  // 1. state.db (via SqliteConnection, which triggers initSchema + migrateSchema)
  const stateDbPath = path.join(resolvedWorkspace, '.pd', 'state.db');
  if (!confirm) {
    // dry-run: report what would be initialized without touching disk
    databases.push({
      name: DB_NAMES.state,
      path: stateDbPath,
      tables: ['tasks', 'runs', 'artifacts', 'commits', 'principle_candidates',
        'pi_artifacts', 'approvals', 'activations', 'intent_decisions', 'schema_version'],
      status: 'skipped',
      warnings: [],
    });
  } else {
    try {
      const conn = new SqliteConnection({ workspaceDir: resolvedWorkspace, readonly: false });
      try {
        conn.getDb(); // triggers initSchema + migrateSchema
        const connWarnings = conn.getSchemaInitWarnings();
        if (connWarnings.length > 0) {
          warnings.push(...connWarnings.map(w => `${DB_NAMES.state}: ${w}`));
        }
        databases.push({
          name: DB_NAMES.state,
          path: stateDbPath,
          tables: ['tasks', 'runs', 'artifacts', 'commits', 'principle_candidates',
            'pi_artifacts', 'approvals', 'activations', 'intent_decisions', 'schema_version'],
          status: 'initialized',
          warnings: connWarnings,
        });
      } finally {
        conn.close();
      }
    } catch (err) {
      const reason = err instanceof Error ? err.message : String(err);
      databases.push({
        name: DB_NAMES.state,
        path: stateDbPath,
        tables: [],
        status: 'failed',
        warnings: [reason],
      });
      return {
        ok: false,
        mode: 'confirm',
        workspace: resolvedWorkspace,
        databases,
        warnings,
        reason: `state.db initialization failed: ${reason}`,
        nextAction: 'Check workspace directory permissions and disk space, then retry.',
      };
    }
  }

  // 2. trajectory.db (via initTrajectorySchema)
  if (!confirm) {
    databases.push({
      name: DB_NAMES.trajectory,
      path: path.join(resolvedWorkspace, '.state', 'trajectory.db'),
      tables: ['schema_version', 'ingest_checkpoint', 'sessions', 'assistant_turns',
        'user_turns', 'tool_calls', 'pain_events', 'gate_blocks', 'trust_changes',
        'principle_events', 'task_outcomes', 'correction_samples', 'sample_reviews',
        'exports_audit', 'evolution_tasks', 'evolution_events'],
      status: 'skipped',
      warnings: [],
    });
  } else {
    try {
      const result = initTrajectorySchema(resolvedWorkspace);
      if (result.warnings.length > 0) {
        warnings.push(...result.warnings.map((w: string) => `${DB_NAMES.trajectory}: ${w}`));
      }
      databases.push({
        name: DB_NAMES.trajectory,
        path: path.join(resolvedWorkspace, '.state', 'trajectory.db'),
        tables: result.tables,
        status: 'initialized',
        warnings: result.warnings,
      });
    } catch (err) {
      const reason = err instanceof Error ? err.message : String(err);
      databases.push({
        name: DB_NAMES.trajectory,
        path: path.join(resolvedWorkspace, '.state', 'trajectory.db'),
        tables: [],
        status: 'failed',
        warnings: [reason],
      });
      return {
        ok: false,
        mode: 'confirm',
        workspace: resolvedWorkspace,
        databases,
        warnings,
        reason: `trajectory.db initialization failed: ${reason}`,
        nextAction: 'Check workspace directory permissions and disk space, then retry.',
      };
    }
  }

  // 3. subagent_workflows.db (via initWorkflowSchema)
  if (!confirm) {
    databases.push({
      name: DB_NAMES.workflow,
      path: path.join(resolvedWorkspace, '.state', 'subagent_workflows.db'),
      tables: ['schema_version', 'subagent_workflows', 'subagent_workflow_events'],
      status: 'skipped',
      warnings: [],
    });
  } else {
    try {
      const result = initWorkflowSchema(resolvedWorkspace);
      if (result.warnings.length > 0) {
        warnings.push(...result.warnings.map((w: string) => `${DB_NAMES.workflow}: ${w}`));
      }
      databases.push({
        name: DB_NAMES.workflow,
        path: path.join(resolvedWorkspace, '.state', 'subagent_workflows.db'),
        tables: result.tables,
        status: 'initialized',
        warnings: result.warnings,
      });
    } catch (err) {
      const reason = err instanceof Error ? err.message : String(err);
      databases.push({
        name: DB_NAMES.workflow,
        path: path.join(resolvedWorkspace, '.state', 'subagent_workflows.db'),
        tables: [],
        status: 'failed',
        warnings: [reason],
      });
      return {
        ok: false,
        mode: 'confirm',
        workspace: resolvedWorkspace,
        databases,
        warnings,
        reason: `subagent_workflows.db initialization failed: ${reason}`,
        nextAction: 'Check workspace directory permissions and disk space, then retry.',
      };
    }
  }

  // Verify state.db schema conformance after initialization (confirm mode only)
  if (confirm) {
    try {
      const conformance = new SchemaConformanceReadModel({ workspaceDir: resolvedWorkspace });
      const result = conformance.check();
      if (result.overallStatus === 'error') {
        warnings.push(`state.db schema conformance check returned 'error' — some tables or indexes may be missing`);
      }
    } catch (err) {
      // Non-fatal: schema conformance check is a post-verification step
      warnings.push(`schema conformance verification skipped: ${err instanceof Error ? err.message : String(err)}`);
    }
  }

  // 4. config.yaml — scaffold the single source of truth (P0: runtime discovery)
  const config = buildConfigInitResult(resolvedWorkspace, confirm);
  if (config.status === 'failed') {
    return {
      ok: false,
      mode: 'confirm',
      workspace: resolvedWorkspace,
      databases,
      config,
      warnings,
      reason: config.warnings[0] ?? 'config.yaml initialization failed',
      nextAction: 'Check .pd directory permissions and disk space, then re-run `pd runtime init --confirm`.',
    };
  }

  return {
    ok: true,
    mode: confirm ? 'confirm' : 'dry-run',
    workspace: resolvedWorkspace,
    databases,
    config,
    warnings,
  };
}

// ── Text formatting ──────────────────────────────────────────────────────────

function formatTextOutput(output: RuntimeInitOutput): string {
  const lines: string[] = [];

  lines.push('PD Runtime Init');
  lines.push(`mode: ${output.mode}`);
  lines.push(`workspace: ${output.workspace}`);
  lines.push('');

  for (const db of output.databases) {
    const icon = db.status === 'initialized' ? '[+]' :
                 db.status === 'verified' ? '[v]' :
                 db.status === 'skipped' ? '[ ]' : '[x]';
    lines.push(`${icon} ${db.name} (${db.status})`);
    lines.push(`    path: ${db.path}`);
    if (db.tables.length > 0) {
      lines.push(`    tables: ${db.tables.length} (${db.tables.slice(0, 5).join(', ')}${db.tables.length > 5 ? ', ...' : ''})`);
    }
    for (const w of db.warnings) {
      lines.push(`    warning: ${w}`);
    }
  }

  if (output.config) {
    const icon = output.config.status === 'initialized' ? '[+]' :
                 output.config.status === 'verified' ? '[v]' :
                 output.config.status === 'skipped' ? '[ ]' : '[x]';
    lines.push(`${icon} config.yaml (${output.config.status})`);
    lines.push(`    path: ${output.config.path}`);
    for (const w of output.config.warnings) {
      lines.push(`    warning: ${w}`);
    }
  }

  if (output.warnings.length > 0) {
    lines.push('');
    lines.push('Warnings:');
    for (const w of output.warnings) {
      lines.push(`  [!] ${w}`);
    }
  }

  if (!output.ok && output.reason) {
    lines.push('');
    lines.push(`Error: ${output.reason}`);
    if (output.nextAction) {
      lines.push(`→ ${output.nextAction}`);
    }
  }

  return lines.join('\n');
}

// ── CLI handler ──────────────────────────────────────────────────────────────

export interface RuntimeInitOptions {
  workspace?: string;
  dryRun?: boolean;
  confirm?: boolean;
  json?: boolean;
}

export async function handleRuntimeInit(opts: RuntimeInitOptions): Promise<void> {
  // cli-4: --dry-run and --confirm are mutually exclusive
  if (opts.dryRun && opts.confirm) {
    process.exitCode = emitFlagConflict({ json: opts.json ?? false });
    return;
  }

  const workspaceDir = opts.workspace
    ? path.resolve(opts.workspace)
    : resolveWorkspaceDir();

  // Default is dry-run; --confirm opts in to actual initialization
  const confirm = opts.confirm === true;

  try {
    const output = buildRuntimeInitOutput(workspaceDir, confirm);
    emitResult(output, { json: opts.json ?? false, formatText: formatTextOutput });

    if (!output.ok) {
      process.exitCode = 1; // cli-2: set exit code, no process.exit()
    }
  } catch (err) {
    process.exitCode = emitError(err, {
      json: opts.json ?? false,
      nextAction: 'Check workspace directory and permissions, then retry.',
    });
  }
}

