import type { PIArtifactSnapshot, CanActivateResult, ChannelWriter, WriterInput, WriterResult } from './activation-types.js';

function isRecord(value: unknown): value is Record<string, unknown> {
  return value !== null && typeof value === 'object' && !Array.isArray(value);
}

/**
 * ⚠️ DISPLAY / RESOLUTION ONLY — never an identity source.
 *
 * This helper intentionally keeps its lenient multi-step fallback (column →
 * `content.principleId` → `content.sourcePrincipleId` → `principleDraft.title`)
 * because display and approval-grouping surfaces need to show *something* for
 * legacy artifacts that were activated before identities were stamped.
 *
 * It must NOT be used to mint or gate a principle identity: its last fallback
 * returns `principleDraft.title` — a natural-language string generated by the
 * philosopher — which is exactly how content came to masquerade as identity and
 * fragmented the principle identity space (Phase 3 design audit,
 * `docs/architecture/principle-identity-reconciliation.md`, finding F1).
 *
 * For anything that WRITES or GATES an activation use
 * {@link resolveActivationPrincipleId} instead (fail-closed).
 */
function extractPrincipleId(artifact: PIArtifactSnapshot): string | null {
  if (typeof artifact.sourcePrincipleId === 'string') {
    const sourceId = artifact.sourcePrincipleId.trim();
    if (sourceId !== '') return sourceId;
  }
  try {
    const parsed = JSON.parse(artifact.contentJson);
    if (!isRecord(parsed)) return null;
    if (typeof parsed.principleId === 'string' && parsed.principleId.trim() !== '') {
      return parsed.principleId.trim();
    }
    if (typeof parsed.sourcePrincipleId === 'string' && parsed.sourcePrincipleId.trim() !== '') {
      return parsed.sourcePrincipleId.trim();
    }
    if (isRecord(parsed.principleDraft)) {
      const draft = parsed.principleDraft;
      if (typeof draft.title === 'string' && draft.title.trim() !== '') {
        return draft.title.trim();
      }
    }
  } catch {
    return null;
  }
  return null;
}

/** Ledger principle ids are UUIDs — `_tree.principles` is keyed by `randomUUID()`. */
const PRINCIPLE_ID_UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

/**
 * I3 — ACTIVATION IDENTITY BOUNDARY (fail-closed).
 *
 * Phase 3 (Principle Identity Reconciliation,
 * `docs/architecture/principle-identity-reconciliation.md`): the ONLY identity
 * an activation may carry is the `pi_artifacts.source_principle_id` column value
 * when it is a ledger-shaped principle UUID. Everything else — `principleDraft`
 * titles, content-level ids, any text form — is refused (`null`), because a
 * content-derived identity is how `principle_applications` / `activations`
 * ended up keyed by philosopher titles instead of ledger UUIDs.
 *
 * Deliberately NOT here (and never re-add):
 *   - contentJson fallbacks (`principleId` / `sourcePrincipleId` / draft title)
 *   - text/fuzzy matching against ledger principles
 *
 * Ledger *membership* is validated by the ledger-backed call sites
 * (`PrincipleTreeLedgerAdapter.hasPrinciple` / `activatePrinciple` and
 * pd-console's `resolveLedgerPrincipleId`); this boundary guarantees the value
 * is at least UUID-shaped, so a title can never become a durable identity.
 *
 * The returned value is LOWERCASE-normalized: ledger keys are minted by
 * `randomUUID()` (always lowercase), so an uppercase UUID that passes the shape
 * check would otherwise miss `hasPrinciple` and be refused as
 * `principle_not_in_ledger` — a case-only mismatch masquerading as data drift.
 *
 * @returns the trimmed, lowercase UUID, or `null` when the artifact carries no
 *          usable identity — callers must refuse with
 *          `no_principle_id_in_artifact`.
 */
export function resolveActivationPrincipleId(artifact: PIArtifactSnapshot): string | null {
  const raw = artifact.sourcePrincipleId;
  if (typeof raw !== 'string') return null;
  const candidate = raw.trim();
  if (candidate === '') return null;
  if (!PRINCIPLE_ID_UUID_RE.test(candidate)) return null;
  return candidate.toLowerCase();
}

export class PromptWriter implements ChannelWriter {
  readonly channel = 'prompt' as const;

  // eslint-disable-next-line @typescript-eslint/class-methods-use-this
  async canActivate(artifact: PIArtifactSnapshot): Promise<CanActivateResult> {
    if (artifact.artifactKind !== 'principle') {
      return { ok: false, reason: 'artifact_kind_not_principle', riskLevel: 'low' };
    }
    if (artifact.validationStatus !== 'validated') {
      return { ok: false, reason: `artifact_validation_status_${artifact.validationStatus}`, riskLevel: 'low' };
    }
    // Identity gating deliberately does NOT live here anymore (Owner review of
    // PR #1856, P1): the writer only knows artifact shape — ledger membership
    // requires the ActivationDispatcher's ledgerIdentity deps. The dispatcher
    // gates BOTH paths (enqueueForApproval + activateArtifact) so the identity
    // check happens once, before the approval queue and before the activation
    // commit, against the ledger.
    return { ok: true, riskLevel: 'low' };
  }

  // eslint-disable-next-line @typescript-eslint/class-methods-use-this
  async activate(input: WriterInput, _artifact: PIArtifactSnapshot): Promise<WriterResult> {
    return {
      activationId: `act_prompt_${input.principleId}`,
      action: 'prompt_activate',
      targetRef: `ledger://${input.principleId}`,
    };
  }
}

export class DeferArchiveWriter implements ChannelWriter {
  readonly channel = 'defer_archive' as const;

  // eslint-disable-next-line @typescript-eslint/class-methods-use-this
  async canActivate(artifact: PIArtifactSnapshot): Promise<CanActivateResult> {
    if (artifact.artifactKind !== 'principle') {
      return { ok: false, reason: 'artifact_kind_not_principle', riskLevel: 'low' };
    }
    if (artifact.validationStatus !== 'validated') {
      return { ok: false, reason: `artifact_validation_status_${artifact.validationStatus}`, riskLevel: 'low' };
    }
    // See PromptWriter.canActivate: identity gating moved to the dispatcher.
    return { ok: true, riskLevel: 'low' };
  }

  // eslint-disable-next-line @typescript-eslint/class-methods-use-this
  async activate(input: WriterInput, _artifact: PIArtifactSnapshot): Promise<WriterResult> {
    return {
      activationId: `act_archive_${input.principleId}`,
      action: 'defer_archive',
      targetRef: `ledger://${input.principleId}#archived`,
    };
  }
}

export { extractPrincipleId };
