/**
 * Adversarial case → GoldenTrace conversion (RuleHost MVP Activation, ADR-0014
 * Amendment 2026-06-17, PRD Decision 11d).
 *
 * Adversarial cases are generated by the Evaluator LLM to attack the Artificer's
 * generated code. Every adversarial case is conceptually a NEGATIVE expectation
 * (the attack should reveal a gap), so the converted GoldenTrace marks all
 * cases kind='negative'.
 *
 * IMPORTANT design contract: the converted trace intentionally does NOT pass
 * `validateGoldenTrace()` on its own, because it has no positive case. The
 * caller (Evaluator.succeedTask, Phase 5) must append a positive case (or
 * merge with the Artificer's golden trace) before the combined trace can be
 * replayed. This is pinned by adversarial-case.test.ts.
 */
import type { GoldenTrace, GoldenTraceCase, GoldenTraceDecision } from '../golden-trace.js';

const ADVERSARIAL_ATTACK_TYPES: ReadonlySet<string> = new Set(['boundary', 'omission', 'inversion']);
const GOLDEN_TRACE_DECISIONS: ReadonlySet<string> = new Set(['allow', 'block', 'propose_correction']);

function isGoldenTraceDecision(v: string): v is GoldenTraceDecision {
  return GOLDEN_TRACE_DECISIONS.has(v);
}

export type AdversarialConversionResult =
  | { readonly ok: true; readonly trace: GoldenTrace }
  | { readonly ok: false; readonly reason: string };

function isRecord(v: unknown): v is Record<string, unknown> {
  return v !== null && typeof v === 'object' && !Array.isArray(v);
}

/**
 * Convert AdversarialCase[] (all attacks, all negative) into a GoldenTrace.
 *
 * Does NOT synthesize a positive case — see file header. The caller is
 * responsible for ensuring the replayed trace has ≥1 positive case, either
 * by merging with the Artificer's golden trace or appending one.
 */
export function adversarialCasesToGoldenTrace(cases: unknown): AdversarialConversionResult {
  if (!Array.isArray(cases)) {
    return { ok: false, reason: 'adversarialCases must be an array' };
  }
  if (cases.length === 0) {
    return { ok: false, reason: 'adversarialCases must contain at least one case, got 0' };
  }

  const mappedCases: GoldenTraceCase[] = [];
  for (let index = 0; index < cases.length; index += 1) {
    const entry = cases[index];
    const prefix = `adversarialCases[${index}]`;
    if (!isRecord(entry)) {
      return { ok: false, reason: `${prefix} must be an object` };
    }
    if (!Object.hasOwn(entry, 'caseId') || typeof entry.caseId !== 'string' || entry.caseId.trim() === '') {
      return { ok: false, reason: `${prefix}.caseId must be a non-empty string` };
    }
    if (!Object.hasOwn(entry, 'attackType') || typeof entry.attackType !== 'string' || !ADVERSARIAL_ATTACK_TYPES.has(entry.attackType)) {
      return { ok: false, reason: `${prefix}.attackType must be one of boundary|omission|inversion, got ${String(entry.attackType)}` };
    }
    if (!Object.hasOwn(entry, 'toolName') || typeof entry.toolName !== 'string' || entry.toolName.trim() === '') {
      return { ok: false, reason: `${prefix}.toolName must be a non-empty string` };
    }
    if (!Object.hasOwn(entry, 'params') || !isRecord(entry.params)) {
      return { ok: false, reason: `${prefix}.params must be an object` };
    }
    if (
      !Object.hasOwn(entry, 'expectedDecision')
      || typeof entry.expectedDecision !== 'string'
      || !isGoldenTraceDecision(entry.expectedDecision)
    ) {
      return { ok: false, reason: `${prefix}.expectedDecision must be one of allow|block|propose_correction, got ${String(entry.expectedDecision)}` };
    }
    if (!Object.hasOwn(entry, 'rationale') || typeof entry.rationale !== 'string' || entry.rationale.trim() === '') {
      return { ok: false, reason: `${prefix}.rationale must be a non-empty string` };
    }

    mappedCases.push({
      caseId: entry.caseId,
      // All adversarial cases are attacks → negative expectations.
      kind: 'negative',
      toolName: entry.toolName,
      params: entry.params,
      // Narrowed by isGoldenTraceDecision above (Runtime Contract Rule 2).
      expectedDecision: entry.expectedDecision,
    });
  }

  const trace: GoldenTrace = {
    traceId: `golden-trace-adversarial-${Date.now().toString(36)}`,
    version: 1,
    createdAt: new Date().toISOString(),
    cases: mappedCases,
  };

  return { ok: true, trace };
}
