/**
 * Dreamer output types and validator (PRI-67).
 *
 * Dreamer generates 2-3 diverse candidate corrections for principle violations.
 * Output is consumed by Philosopher (next stage in dreamer→philosopher→scribe chain).
 *
 * Follows ADR-0003 peer runner contract: DreamerRunner does NOT directly invoke
 * Philosopher/Scribe — it returns artifact/proposal for host layer to enqueue.
 *
 * @see docs/adr/0003-peer-agent-state-machine-orchestration.md
 */
import type { PDErrorCategory } from '../error-categories.js';
import { Type, type Static } from '@sinclair/typebox';

// ── Output Types ─────────────────────────────────────────────────────────────

/**
 * A single candidate correction generated by Dreamer.
 *
 * Represents a different valid approach to addressing a principle violation
 * observed in a session trajectory.
 */
export interface DreamerCandidate {
  /** 0-based index within the candidate list */
  readonly candidateIndex: number;
  /** What the agent did wrong in the observed case */
  readonly badDecision: string;
  /** What the agent should have done instead */
  readonly betterDecision: string;
  /** Why this alternative is better than the bad decision */
  readonly rationale: string;
  /** Confidence score [0, 1] */
  readonly confidence: number;
  /** LLM-judged risk level of applying this candidate */
  readonly riskLevel: 'low' | 'medium' | 'high';
  /** Strategic lens through which this candidate was evaluated */
  readonly strategicPerspective: string;
}

/**
 * The structured output of a Dreamer run.
 *
 * Produced by the LLM runtime via PDRuntimeAdapter, validated by DreamerValidator,
 * and stored as a RunRecord output. The host layer (orchestrator or committer)
 * converts this into Philosopher's input.
 */
export interface DreamerOutput {
  /** Whether the Dreamer LLM call succeeded and produced valid output */
  readonly valid: boolean;
  /** Task ID this output belongs to */
  readonly taskId: string;
  /** List of candidate corrections (1-5 items) */
  readonly candidates: readonly DreamerCandidate[];
  /** Optional principle this Dreamer run was targeting */
  readonly sourcePrincipleId?: string;
  /** Optional pain signal that triggered this Dreamer run */
  readonly sourcePainId?: string;
  /** Artifact/context references consumed as input */
  readonly contextRefs: readonly string[];
  /** ISO-8601 timestamp when output was generated */
  readonly generatedAt: string;
  /** Human-readable explanation when valid=false */
  readonly reason?: string;
}

// ── TypeBox Schema ──────────────────────────────────────────────────────────

export const DreamerCandidateSchema = Type.Object({
  candidateIndex: Type.Number(),
  badDecision: Type.String({ minLength: 1 }),
  betterDecision: Type.String({ minLength: 1 }),
  rationale: Type.String({ minLength: 1 }),
  confidence: Type.Number({ minimum: 0, maximum: 1 }),
  riskLevel: Type.Union([Type.Literal('low'), Type.Literal('medium'), Type.Literal('high')]),
  strategicPerspective: Type.String({ minLength: 1 }),
});

export const DreamerOutputV1Schema = Type.Object({
  valid: Type.Boolean(),
  taskId: Type.String({ minLength: 1 }),
  candidates: Type.Array(DreamerCandidateSchema, { minItems: 1, maxItems: 5 }),
  sourcePrincipleId: Type.Optional(Type.String()),
  sourcePainId: Type.Optional(Type.String()),
  contextRefs: Type.Array(Type.String()),
  generatedAt: Type.String({ minLength: 1 }),
  reason: Type.Optional(Type.String()),
});

export type DreamerOutputV1 = Static<typeof DreamerOutputV1Schema>;

// ── Validation Result ────────────────────────────────────────────────────────

/**
 * Result of DreamerOutput validation.
 */
export interface DreamerValidationResult {
  readonly valid: boolean;
  readonly errors: readonly string[];
  readonly errorCategory?: PDErrorCategory;
}

// ── Validator Interface ─────────────────────────────────────────────────────────

/**
 * Validator interface consumed by DreamerRunner.
 *
 * Production code must use DefaultDreamerValidator (strict validation).
 * PassThroughDreamerValidator is test-only and must not be used in production paths.
 */
export interface DreamerValidator {
  /** Validate untrusted output. Accepts `unknown` — must perform runtime checks (ERR-001). */
  validate(output: unknown, taskId: string): Promise<DreamerValidationResult>;
}

const VALID_RISK_LEVELS = new Set(['low', 'medium', 'high']);

export class DefaultDreamerValidator implements DreamerValidator {
  // eslint-disable-next-line @typescript-eslint/class-methods-use-this
  async validate(output: unknown, taskId: string): Promise<DreamerValidationResult> {
    const errors: string[] = [];

    if (typeof output !== 'object' || output === null) {
      return { valid: false, errors: ['Output is not an object'], errorCategory: 'output_invalid' };
    }

    // Narrow to Record for property access — all fields still treated as untrusted.
    const record = output as Record<string, unknown>;

    if (record.taskId !== taskId) {
      errors.push(`taskId mismatch: expected ${taskId}, got ${String(record.taskId)}`);
    }

    if (record.valid !== true) {
      errors.push('output.valid must be true');
    }

    if (!Array.isArray(record.candidates)) {
      errors.push('candidates must be an array');
    } else {
      if (record.candidates.length < 1 || record.candidates.length > 5) {
        errors.push('candidates must have 1-5 items');
      }
      for (let i = 0; i < record.candidates.length; i++) {
        const c = record.candidates[i] as Record<string, unknown> | undefined;
        if (!c) {
          errors.push(`candidates[${i}] is null/undefined`);
          continue;
        }
        if (typeof c.candidateIndex !== 'number') errors.push(`candidates[${i}].candidateIndex must be number`);
        if (typeof c.badDecision !== 'string' || (c.badDecision).trim() === '') errors.push(`candidates[${i}].badDecision must be non-empty string`);
        if (typeof c.betterDecision !== 'string' || (c.betterDecision).trim() === '') errors.push(`candidates[${i}].betterDecision must be non-empty string`);
        if (typeof c.rationale !== 'string' || (c.rationale).trim() === '') errors.push(`candidates[${i}].rationale must be non-empty string`);
        if (typeof c.confidence !== 'number') errors.push(`candidates[${i}].confidence must be number`);
        else if (c.confidence < 0 || c.confidence > 1) errors.push(`candidates[${i}].confidence must be in [0, 1]`);
        if (typeof c.riskLevel !== 'string' || !VALID_RISK_LEVELS.has(c.riskLevel)) errors.push(`candidates[${i}].riskLevel must be low|medium|high`);
        if (typeof c.strategicPerspective !== 'string' || (c.strategicPerspective).trim() === '') errors.push(`candidates[${i}].strategicPerspective must be non-empty string`);
      }
    }

    if (!Array.isArray(record.contextRefs)) {
      errors.push('contextRefs must be an array');
    }

    if (typeof record.generatedAt !== 'string' || (record.generatedAt).trim() === '') {
      errors.push('generatedAt must be non-empty string');
    }

    return errors.length > 0
      ? { valid: false, errors, errorCategory: 'output_invalid' }
      : { valid: true, errors: [] };
  }
}

/**
 * Pass-through validator — accepts all output.
 *
 * @deprecated Test-only. Do NOT use in production paths.
 *   Production code must use DefaultDreamerValidator which enforces schema,
 *   candidate count (1-5), confidence range (0..1), and riskLevel validation.
 * @internal
 */
export class PassThroughDreamerValidator implements DreamerValidator {
  // eslint-disable-next-line @typescript-eslint/class-methods-use-this
  async validate(_output: unknown, _taskId: string): Promise<DreamerValidationResult> {
    return { valid: true, errors: [] };
  }
}