/**
 * Dreamer output types and validator (PRI-67).
 *
 * Dreamer generates 2-3 diverse candidate corrections for principle violations.
 * Output is consumed by Philosopher (next stage in dreamer→philosopher→scribe chain).
 *
 * Follows ADR-0003 peer runner contract: DreamerRunner does NOT directly invoke
 * Philosopher/Scribe — it returns artifact/proposal for host layer to enqueue.
 *
 * @see docs/adr/0003-peer-agent-state-machine-orchestration.md
 */
import type { PDErrorCategory } from '../error-categories.js';

// ── Output Types ─────────────────────────────────────────────────────────────

/**
 * A single candidate correction generated by Dreamer.
 *
 * Represents a different valid approach to addressing a principle violation
 * observed in a session trajectory.
 */
export interface DreamerCandidate {
  /** 0-based index within the candidate list */
  readonly candidateIndex: number;
  /** What the agent did wrong in the observed case */
  readonly badDecision: string;
  /** What the agent should have done instead */
  readonly betterDecision: string;
  /** Why this alternative is better than the bad decision */
  readonly rationale: string;
  /** Confidence score [0, 1] */
  readonly confidence: number;
  /** LLM-judged risk level of applying this candidate */
  readonly riskLevel: 'low' | 'medium' | 'high';
  /** Strategic lens through which this candidate was evaluated */
  readonly strategicPerspective: string;
}

/**
 * The structured output of a Dreamer run.
 *
 * Produced by the LLM runtime via PDRuntimeAdapter, validated by DreamerValidator,
 * and stored as a RunRecord output. The host layer (orchestrator or committer)
 * converts this into Philosopher's input.
 */
export interface DreamerOutput {
  /** Whether the Dreamer LLM call succeeded and produced valid output */
  readonly valid: boolean;
  /** Task ID this output belongs to */
  readonly taskId: string;
  /** List of candidate corrections (1-5 items) */
  readonly candidates: readonly DreamerCandidate[];
  /** Optional principle this Dreamer run was targeting */
  readonly sourcePrincipleId?: string;
  /** Optional pain signal that triggered this Dreamer run */
  readonly sourcePainId?: string;
  /** Artifact/context references consumed as input */
  readonly contextRefs: readonly string[];
  /** ISO-8601 timestamp when output was generated */
  readonly generatedAt: string;
  /** Human-readable explanation when valid=false */
  readonly reason?: string;
}

// ── Validation Result ────────────────────────────────────────────────────────

/**
 * Result of DreamerOutput validation.
 */
export interface DreamerValidationResult {
  readonly valid: boolean;
  readonly errors: readonly string[];
  readonly errorCategory?: PDErrorCategory;
}

// ── Validator Interface ─────────────────────────────────────────────────────────

/**
 * Validator interface consumed by DreamerRunner.
 *
 * Initial scope uses PassThroughDreamerValidator (accepts all output).
 * Full validation (schema + semantic + confidence range) is future scope.
 */
export interface DreamerValidator {
  validate(output: DreamerOutput, taskId: string): Promise<DreamerValidationResult>;
}

/**
 * Pass-through validator — accepts all output (initial scope).
 *
 * @deprecated Temporary implementation. Real DreamerValidator with schema
 *   validation, candidate count (1-5), confidence range (0..1), and
 *   riskLevel validation must be implemented in a future PRI-67 follow-up.
 *   When a real validator rejects output, DreamerRunner retries via retryOrFail.
 */
export class PassThroughDreamerValidator implements DreamerValidator {
  // eslint-disable-next-line @typescript-eslint/class-methods-use-this
  async validate(_output: DreamerOutput, _taskId: string): Promise<DreamerValidationResult> {
    return { valid: true, errors: [] };
  }
}