/**
 * Template Generator for Principle Compiler
 *
 * Generates RuleHost sandbox code from PainPattern descriptors.
 * Produces self-contained JS modules with `const meta` and
 * `function evaluate(input, helpers)` that can be loaded at runtime.
 *
 * PRI-439 Phase 2: canonical dialect is bare `function evaluate(input, helpers)`
 * — no ESM `export` keyword (forbidden by checkForbiddenPatterns).
 * Default return is `{ decision: 'allow', matched: false, reason: '...' }`
 * (matched=false requires decision='allow').
 *
 * SECURITY: All interpolated values use JSON.stringify or safe helpers
 * to prevent code injection through principleId, coversCondition, or regex patterns.
 *
 * PRI-44: Pure domain logic, zero infrastructure dependency.
 */

export interface PainPattern {
  toolName: string;
  pathRegex?: string;
  commandRegex?: string;
  contentRegex?: string;
  errorType?: string;
}

function toAutoName(principleId: string): string {
  return `Auto_${principleId}`;
}

function toAutoRuleId(principleId: string): string {
  return `R_${principleId}_auto`;
}

function buildBranch(principleId: string, pattern: PainPattern): string {
  const conditions: string[] = [];

  conditions.push(`input.action.toolName === ${JSON.stringify(pattern.toolName)}`);

  if (pattern.pathRegex) {
    conditions.push(`new RegExp(${JSON.stringify(pattern.pathRegex)}).test(input.action.normalizedPath || '')`);
  }

  if (pattern.commandRegex) {
    conditions.push(`new RegExp(${JSON.stringify(pattern.commandRegex)}).test(input.action.paramsSummary.command || '')`);
  }

  if (pattern.contentRegex) {
    conditions.push(
      `new RegExp(${JSON.stringify(pattern.contentRegex)}).test(input.action.paramsSummary.content || input.action.paramsSummary.new_string || '')`,
    );
  }

  const guard = conditions.join(' && ');
  const reason = `[${principleId}] Blocked by auto-generated rule`;

  return (
    `  if (${guard}) {\n` +
    `    return { decision: 'block', matched: true, reason: ${JSON.stringify(reason)} };\n` +
    `  }`
  );
}

export function generateFromTemplate(
  principleId: string,
  coversCondition: string,
  patterns: PainPattern[],
): string | null {
  if (patterns.length === 0) {
    return null;
  }

  const name = toAutoName(principleId);
  const ruleId = toAutoRuleId(principleId);
  const compiledAt = new Date().toISOString();

  const branches = patterns
    .map((p) => buildBranch(principleId, p))
    .join('\n');

  return (
    `// Auto-generated by Principle Compiler\n` +
    `const meta = {\n` +
    `  name: ${JSON.stringify(name)},\n` +
    `  version: '1.0.0',\n` +
    `  ruleId: ${JSON.stringify(ruleId)},\n` +
    `  coversCondition: ${JSON.stringify(coversCondition)},\n` +
    `  compiledAt: ${JSON.stringify(compiledAt)},\n` +
    `  sourcePrincipleId: ${JSON.stringify(principleId)},\n` +
    `};\n\n` +
    `function evaluate(input, helpers) {\n` +
    `${branches}\n` +
    `  return { decision: 'allow', matched: false, reason: 'rule not applicable' };\n` +
    `}\n`
  );
}
